# Generated by Django 5.2.8 on 2025-12-11 14:44

import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the record is available and in use. A deleted record is always inactive.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if the record has been marked as deleted, but still exists in the database.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='/default/product_placeholder.png', null=True, upload_to='brands/logos/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalog_bra_is_acti_5c9548_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the record is available and in use. A deleted record is always inactive.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if the record has been marked as deleted, but still exists in the database.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalog_cat_is_acti_09f4ba_idx'), models.Index(fields=['tree_id', 'lft'], name='catalog_category_tree_id_lc185')],
                'unique_together': {('parent', 'name')},
            },
        ),
    ]
