# Generated by Django 5.2.8 on 2025-12-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brand',
            new_name='catalog_bra_is_acti_5c9548_idx',
            old_name='brand_is_acti_30b84a_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_is_acti_09f4ba_idx',
            old_name='category_is_acti_6fc5dc_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_categor_a6606d_idx',
            old_name='product_categor_81a45a_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='catalog_pro_product_a99e46_idx',
            old_name='product_ima_product_b48ab6_idx',
        ),
        migrations.RenameIndex(
            model_name='productspecification',
            new_name='catalog_pro_product_cb82d4_idx',
            old_name='product_spe_product_36c63b_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_product_ee4f5c_idx',
            old_name='product_var_product_dd3e63_idx',
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productmeta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productspecification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
    ]
