# Generated by Django 5.2.8 on 2025-12-11 14:52

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attribute_specification_attributevalue_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='catalog.productvariant')),
                ('qr_code', models.ImageField(blank=True, editable=False, upload_to='products/qr_codes/')),
                ('weight', models.CharField(blank=True, help_text='Weight with unit (e.g., 500g, 1.5kg)', max_length=50)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions (e.g., 10x20x5 cm)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Meta',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='products/images/')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['product_variant', 'is_primary'], name='catalog_pro_product_a99e46_idx')],
            },
        ),
    ]
