# Generated by Django 5.2.8 on 2025-12-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_brand_is_acti_30b84a_idx_catalog_bra_is_acti_5c9548_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table=None,
        ),
    ]
