# Generated by Django 5.2.8 on 2025-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productmeta_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(default=13123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
