# Generated by Django 5.2.8 on 2025-12-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_attribute_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='specification',
            table=None,
        ),
    ]
