# Generated by Django 5.2.8 on 2025-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(db_index=True, default=3132, max_length=300),
            preserve_default=False,
        ),
    ]
