# Generated by Django 5.2.8 on 2025-12-15 19:51

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CLP', max_digits=12, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
