# Generated by Django 5.2.8 on 2025-12-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente (reservada)'), ('confirmed', 'Confirmada (pagada)'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('pending', 'Pendiente (reservada)'), ('confirmed', 'Confirmada (pagada)'), ('cancelled', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pendiente (reservada)'), ('confirmed', 'Confirmada (pagada)'), ('cancelled', 'Cancelada')], max_length=20),
        ),
    ]
