# Generated by Django 5.2.8 on 2025-12-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_payment_intent_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='stripe_payment_intent_token',
        ),
    ]
