# Generated by Django 5.2.8 on 2025-12-17 21:27

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_alter_order_total_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CLP', editable=False, max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CLP', 'CLP $'), ('USD', 'USD US$')], default='CLP', editable=False, max_length=3, null=True),
        ),
    ]
