# Generated by Django 5.2.8 on 2025-12-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_stripe_payment_intent_id_order_stripe_payment_intent_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_token',
            new_name='payment_reference',
        ),
    ]
